on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

name: ci
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g npm@8
      - run: node --version
      - run: yarn
      - run: yarn test
